FROM mcr.microsoft.com/playwright/dotnet:v1.59.0-noble

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin \
        --install-dir /usr/share/dotnet \
        --channel 10.0 \
        --version 10.0.201
